### ISSUE TITLE
Is there an elegant way to post data to a relationship?

### ISSUE THREAD

**Issue by MikeCraig418** [fadugyamfi/laravel-api-base#3]
For example:

```
Route::apiResource('schools/{id}/course', /* some class */);
```

Is there an elegant way to attach the School Id to the Course being created? I'm just thinking out loud a bit... 

Thank you!

**Comment by fadugyamfi** [comment]
You can experiment with Nested Restful Resources are indicated in the Laravel Documentation https://laravel.com/docs/8.x/controllers#restful-nested-resources
